#!/bin/csh -f
#
#	MODULE NAME:
#	wfsSetup
#
#	FILENAME:
#	wfsSetup
#
#	INVOCATION:
#	./wfsSetup
#
#	PURPOSE:
#	Sets up the WFS EPICS UAE application directory after unpacking
#
#	DESCRIPTION:
#	This script uses the applSetup utility to set up an EPICS UAE application
#	in the current directory, specifying the options needed by the A&G WFS
#	software.
#
#	PRIOR REQUIREMENTS:
#	The EPICS environment variables should have been defined by executing
#	the EPICS startup script.
#	The GEMINI environment variables should have been defined by
#	executing wfsLogin, or the equivalent Gemini startup script.
#	This script should be executed with the current directory set to the
#	intended top level directory of the WFS EPICS UAE application.
#
#	AUTHOR:
#	Steven M Beard
#
#	HISTORY:
#	$Id: wfsSetup,v 1.1.1.1 1999-05-19 00:04:31 cboyer Exp $
#
#	$Log: not supported by cvs2svn $
#	Revision 1.13  1998/10/12 15:13:38  cics
#	Added reminder about local.vws and resource.def
#
#	Revision 1.12  1998/10/12 14:30:17  cics
#	Link to wfsStart2 added to allow concurrent development
#
#	Revision 1.11  1998/09/28 11:05:30  cics
#	Now depends on cFitsIo as well
#
#	Revision 1.10  1998/07/20 10:54:58  smb
#	PAR directory added.
#
#	Revision 1.9  1998/07/17 14:57:03  smb
#	Uses a better method of testing external dependencies.
#
#	Revision 1.8  1998/07/17 11:33:23  smb
#	Prologue expanded. Modified to check for DHS, ASTLIB and SLALIB libraries.
#
#

# Check the EPICS startup script has been executed.

if ( ${?EPICS} == 0 ) then

   echo "EPICS environment variables have not been defined. Please execute" 
   echo "your local EPICS setup script."
   exit
endif

# Create the soft link to the wfsStart script(s). (This will not be necessary
# if the ./bin/solaris directory is added to the PATH).

if ( !(-e wfsStart) )then
   ln -s ./bin/solaris/wfsStart .
endif

if ( !(-e wfsStart2) )then
   ln -s ./bin/solaris/wfsStart2 .
endif

# Set up the UAE environment. The external dependencies specified can vary
# according to which of the GEMINI environment variables have been defined.
#
# NOTE: This elaborate scheme allows the software to be developed at
# different sites which may or may not have access to all the necessary
# libraries. On final delivery these checks could be removed and all the
# libraries assumed to exist.

set ext_depends = ""
set ext_comment = ""

if ( ${?GEMINI_DHS} != 0 ) then

	set ext_depends = "`echo ${ext_depends}` -depends `echo ${GEMINI_DHS}`"
	set ext_comment = "`echo ${ext_comment}` DHS"
endif

if ( ${?GEMINI_ASTLIB} != 0 ) then

	set ext_depends = "`echo ${ext_depends}` -depends `echo ${GEMINI_ASTLIB}`"
	set ext_comment = "`echo ${ext_comment}` astLib"
endif

if ( ${?GEMINI_TIMELIB} != 0 ) then

	set ext_depends = "`echo ${ext_depends}` -depends `echo ${GEMINI_TIMELIB}`"
	set ext_comment = "`echo ${ext_comment}` timeLib"
endif

if ( ${?GEMINI_SLALIB} != 0 ) then

	set ext_depends = "`echo ${ext_depends}` -depends `echo ${GEMINI_SLALIB}`"
	set ext_comment = "`echo ${ext_comment}` slaLib"
endif

if ( ${?GEMINI_CFITSIO} != 0 ) then

	set ext_depends = "`echo ${ext_depends}` -depends `echo ${GEMINI_CFITSIO}`"
	set ext_comment = "`echo ${ext_comment}` cFitsIo"
endif


echo "Setting up UAE environment with dependencies on `echo ${ext_comment}` libraries"
applSetup -install `pwd` -T svgm5 -s Makefile.subdirs -I docs -I dspsrc -I par -X sys -X db -X ar `echo ${ext_depends}`

unset ext_depends
unset ext_comment

# For some reason, the applSetup script needs to be executed twice in order to
# work properly.
applSetup

# Remind the user to check their local version of local.vws and resource.def
echo "Please check that startup/local.vws and startup/resource.def are correct."
