# ---------------------------------------------------------------------------
# Zero-setup build: plain `make` works in a fresh checkout.
#
# .applTop and config/ are generated by tools/linux-build/setup.sh, because
# applSetup bakes the checkout's ABSOLUTE path into them -- so they cannot be
# committed. Without a rule for .applTop, a fresh checkout fails with
# "No rule to make target '.applTop'" and the user has to know to run setup.sh
# first. GNU make remakes a missing included makefile when it has a rule for
# it and then restarts, so this rule runs setup.sh on first use.
#
# The same applies when the checkout MOVES (a different container mount, a
# re-clone elsewhere): the recorded path no longer matches, so .applTop is
# discarded and setup.sh regenerates everything against the new location.
ifneq ($(shell cat .applTop 2>/dev/null),APPLIC_TOP = $(CURDIR))
  $(shell rm -f .applTop)
endif
# A .applTop without config/ (an interrupted setup) is just as broken: CONFIG
# is -included, so make silently skips it and runs the first target it finds,
# `release`, which tars the source tree instead of building. Redo setup.
ifeq ($(wildcard config/CONFIG),)
  $(shell rm -f .applTop)
endif

.applTop:
	./tools/linux-build/setup.sh

# The build needs the GEM8.4 environment -- HOST_ARCH above all, or CONFIG
# resolves CONFIG_HOST_ARCH.<whatever> and stops. Set it UNCONDITIONALLY: this
# tree only builds against GEM8.4, and the pipeline's build container already
# carries ADE's EPICS 3.14 environment (HOST_ARCH=linux-x86_64), which must not
# win. A makefile assignment overrides the environment, and `export` passes
# the values to every sub-directory make. Same values as
# /etc/profile.d/gem84.sh, which the spec used to source for the same reason.
export EPICS          := /usr/software/dev/packages/epics/epics3.13.4GEM8.4
export EPICS_BASE     := $(EPICS)/base
export HOST_ARCH      := Linux
export WIND_BASE      := /usr/software/dev/packages/vxworks/tornado2.0/ppc
export WIND_HOST_TYPE := x86-linux
export PATH := $(EPICS_BASE)/bin/$(HOST_ARCH):$(EPICS)/extensions/bin/$(HOST_ARCH):$(WIND_BASE)/host/$(WIND_HOST_TYPE)/bin:$(PATH)

include .applTop
-include $(APPLIC_TOP)/config/CONFIG

APPLIC_DIR_TYPE = sys

-include $(APPLIC_TOP)/config/RULES.Dirs

PROD =  $(notdir $(shell pwd))
TAR =   /usr/bin/tar
COMPRESS = gzip

release:
	$(RM) $(PROD).tar $(PROD).tar.Z $(PROD).tar.gz .xfile
	find * \
	\( -name .applTop     -o \
	   -name .cvsignore   -o \
           -name CVS          -o \
	   -name bin          -o \
	   -name lib          -o \
           -name build.log    -o \
           -name config       -o \
           -name data         -o \
           -name db           -o \
           -name dbd          -o \
           -name include      -o \
           -name javalib      -o \
	   -name cad.rc       -o \
	   -name Distfile     -o \
           -name local.vws    -o \
           -name resource.def -o \
           -name UAE.dist     -o \
	   -name 'O.*'        -o \
           -name '*%'         -o \
           -name '*~'         -o \
	   -name '*.Z'        -o \
           -name '*.gz'          \
	\) -prune -print > .xfile
	$(TAR) cvXf .xfile $(PROD).tar *
	$(COMPRESS) $(PROD).tar
	$(RM) .xfile
