#!/bin/sh -f
#
# Install script for Gemini PWFS2 system
#

host=`hostname`
if [ "`egrep $host /etc/hosts | egrep '^10\.'`" -ne "" ]; then
    site=MK;
else
    site=CP;
fi

applSetup -T svgm5 -s Makefile.subdirs -I docs -I dspsrc -I par -X sys -X ar \
          -depends /gemini/astlib -depends /gemini/slalib \
          -depends /gemini/timelib -depends /gemini/cfitsio/cfitsio \
          -depends /gemini/dhs -site $site $1 > pwfs2Build.log 2>&1

applSetup  >> pwfs2Build.log 2>&1

editUAE()
{
ed UAE.dist << eof >/dev/null
/^FILES4
a
FILES6 = ( \${APPLIC_INSTALL}/bin/asm56000 )
FILES7 = ( \${APPLIC_INSTALL}/IMP_Startup.pwfs2 )
.
w
$
a

(\${FILES6}) -> (\${HOSTS})
        install -R \${DIST_PATH}/bin/asm56000;
(\${FILES7}) -> (\${HOSTS})
        install -R \${DIST_PATH}/IMP_Startup.pwfs2;
.
w
q
eof
}

cd startup
editUAE
cd ..

gmake >> pwfs2Build.log 2>&1

exit 0

