#!/bin/sh -f
#
# Install script for Gemini PWFS system
#

astlib_dir=/gemini/epics3.13.4/astlib/astlib
slalib_dir=/gemini/epics3.13.4/slalib/slalib
timelib_dir=/gemini/epics3.13.4/timelib/timelib
cfitsio_dir=/gemini/epics3.13.4/cfitsio/cfitsio
dhs_dir=/gemini/dhs/dhs

host=`hostname`
if [ "`egrep $host /etc/hosts | egrep '^10\.'`" -ne "" ]; then
    site=MK;
else
    site=CP;
fi

echo `pwd` > APPLIC_INSTALL.txt

cp IMP_Startup$site.pwfs1 IMP_Startup.pwfs1
cp IMP_Startup$site.pwfs2 IMP_Startup.pwfs2

applSetup.pl -T ppc604 -I adl -I capfast -I src -I startup\
             -I docs -I dspsrc -I par -I db\
             -d $astlib_dir -d $slalib_dir \
             -d $timelib_dir -d $cfitsio_dir\
             -d $dhs_dir -S $site $1 > pwfsBuild.log 2>&1

editUAE()
{
ed UAE.dist << eof >/dev/null
$
a

(\${APPLIC_INSTALL}/bin/asm56000) -> (\${DIST_HOST})
        install -R \${DIST_PATH}/bin/asm56000;
(\${APPLIC_INSTALL}/IMP_Startup.pwfs) -> (\${DIST_HOST})
        install -R \${DIST_PATH}/IMP_Startup.pwfs1;
(\${APPLIC_INSTALL}/IMP_Startup.pwfs) -> (\${DIST_HOST})
        install -R \${DIST_PATH}/IMP_Startup.pwfs2;
(\${APPLIC_INSTALL}/RELEASE.NOTES) -> (\${DIST_HOST})
        install -R \${DIST_PATH}/RELEASE.NOTES;
(\${APPLIC_INSTALL}/APPLIC_INSTALL.txt) -> (\${DIST_HOST})
        install -R \${DIST_PATH}/APPLIC_INSTALL.txt;

.
w
q
eof
}

cd startup
editUAE
cd ..

gmake >> pwfsBuild.log 2>&1

exit 0
