#!/bin/csh -f
#+
#  Name:
#    wflman_make_doc
#
#  Purpose:
#    Generate a Gemini VxWorks Software Reference Manual from source code
#    using the "wflman" utility.
#
#  Language:
#    Unix C shell script
#
#  Invocation:
#    wflman_make_doc module_name "author" "initials" "title" doc_number doc_version
#
#  Description:
#    This C shell script processes the source code for the given module
#    with the "wflman" utility, which generates a set of Framemaker ".mif"
#    files containing information extracted from the module and function
#    headers. The shell automatically combines the ".mif" output into
#    a single file which can be imported by Framemaker in one go. Variables
#    describing the title, author, document number and version are
#    automatically defined in the ".mif" file.
#
#  Method:
#    The script first inserts ".mif" format variable definitions into the
#    ".descr.mif" file, which is assumed to have been previously created
#    via wflman for the named VxWorks module. The sed editor is then used
#    to replace each variable by those values given on the command line.
#
#    To guard against mistakes, a backup copy of the existing files are
#    made with ".bak" appended to their names.
#
#  Deficiencies:
#    None of the command-line arguments should contain a "|" character,
#    as this is used as an arbitrary delimiter in the sed script.
#
#  Notes:
#    It would be nice if this script could also import the resultant
#    .mif file into the document template, but this stage of the process
#    has to be done manually.
#
#    Documentation should eventually be installed into the .applTop/docs
#    directory.
#
#  Authors:
#    ND: Nick Dillon (RGO)
#   SMB: Steven Beard (ROE)
#
#  History:
#    15-Oct-1995 (ND):  Original.
#    05-Nov-1997 (SMB): Global change of paragraph format from "Body" to
#                       "Running H/F 1" removed. Module introduction moved
#                       to beginning of document and corrected by adding
#                       paragraph delimiters. Make an automatic copy of
#                       the document template.
#    10-Nov-1997 (SMB): Switch to wflman V2.2.3, which has fewer bugs.
#                       Remove bug work-arounds.
#-
#===============================================================================
#

#
#  Obtain the module name, author name(s), initials, document number and document version
#  from the command arguments.
#
   set module_name = "$1"
   shift
   set author_name = "$1"
   shift
   set initials = "$1"
   shift
   set doc_title = "$1"
   shift
   set doc_number = "$1"
   shift
   set doc_version = "$1"

#
#  The document prefix is a constant. For the time being it is always set to
#  "wfs".
#
   set doc_prefix = "wfs"

#
#  Run the module through wflman.
#
   wflman -omif .applTop/src/${module_name}.c

#
#  Concatenate the intro, summary and description files (the description file 
#  holds a full description of each routine) along with a file holding variable
#  definitions.
#
#   cat ${module_name}.intro.mif ${module_name}.summary.mif wflman.separator.mif ${module_name}.descr.mif wflman.variables.mif >${module_name}.doc.mif.temp
   cat ${module_name}.intro.mif summary_header.mif ${module_name}.summary.mif description_header.mif ${module_name}.descr.mif wflman.variables.mif >${module_name}.doc.mif.temp

#
#  Apply the sed editor to replace the default variable definitions with new
#  values. (Save the old output file if it exists).
#
   if ( -e ${module_name}.doc.mif ) then

      mv -f ${module_name}.doc.mif ${module_name}.doc.mif.bak
   endif

   sed <${module_name}.doc.mif.temp >${module_name}.doc.mif -e "s|DocPrefix|${doc_prefix}|g" -e "s|DocAuthors|${author_name}|g" -e "s|DocInitials|${initials}|g" -e "s|DocNumber|${doc_number}|g" -e "s|DocVersion|${doc_version}|g" -e "s|DocTitle|${module_name} - ${doc_title}|g"

#
#  Remove the temporary file.
#
   rm -f ${module_name}.doc.mif.temp

#
#  Check whether the source code contains any internal functions, and if so
#  compile some extra documentation describing those.
#

   if ( `grep -c 'IGNORED FUNCTION' .applTop/src/${module_name}.c` != 0 ) then

      echo ${module_name} contains internal functions - generating additional documentation.

#
#     Add the wflman paragraph translation options from
#     "wflman_translate_paragraphs.wfl" to the beginning of the source code.
#
      cat wflman_translate_paragraphs.wfl .applTop/src/${module_name}.c >./${module_name}_int.c

#
#     Run this modified module through wflman.
#
      wflman -omif ./${module_name}_int.c
#
#     Concatenate the summary and description files for the internal functions.
#
   cat appendix1_header.mif ${module_name}_int.summary.mif appendix2_header.mif ${module_name}_int.descr.mif >${module_name}_int.doc.mif

#
#     Remove the temporary file.
#
      rm -f ${module_name}_int.c

   endif

#
#  Make a copy of wflman.template.fm with the correct file name, derived from
#  the author initials and document number. (Save the old output file if it
#  exists).
#
   if ( -e ${doc_prefix}_${initials}_${doc_number}.fm ) then

      mv -f ${doc_prefix}_${initials}_${doc_number}.fm ${doc_prefix}_${initials}_${doc_number}.fm.bak
   endif

   cp wflman.template.fm ${doc_prefix}_${initials}_${doc_number}.fm
   chmod +w ${doc_prefix}_${initials}_${doc_number}.fm

#
#  At this point the file ${module_name}.doc.mif needs to be imported into
#  the document ${doc_prefix}_${initials}_${doc_number}.fm. I don't know how to #  do this from within a script, so this stage of the process needs to be done
#  manually. Display a message to this effect. A soft link is used as a reminder
#  of which mif file is associated with which document.
#
   rm -f ${doc_prefix}_${initials}_${doc_number}.doc.mif
   ln -s ${module_name}.doc.mif ${doc_prefix}_${initials}_${doc_number}.doc.mif
   echo Editing finished. Import \"${module_name}.doc.mif\" manually into \"${doc_prefix}_${initials}_${doc_number}.fm\".

   if ( `grep -c 'IGNORED FUNCTION' .applTop/src/${module_name}.c` != 0 ) then

      rm -f ${doc_prefix}_${initials}_${doc_number}_int.doc.mif
      ln -s ${module_name}_int.doc.mif ${doc_prefix}_${initials}_${doc_number}_int.doc.mif
      echo Also import \"${module_name}_int.doc.mif\" at the end of \"${doc_prefix}_${initials}_${doc_number}.fm\".
   endif
