StripConfig                   1.0
Strip.Time.Timespan           300
Strip.Time.SampleInterval     1.000000
Strip.Time.RefreshInterval    1.000000
Strip.Color.Background        65535     65535     65535     
Strip.Color.Foreground        0         0         0         
Strip.Color.Grid              49087     49087     49087     
Strip.Color.LegenedText       65535     65535     65535     
Strip.Color.Color1            0         65535     65535     
Strip.Color.Color2            25443     25443     25443     
Strip.Color.Color3            19532     19532     19532     
Strip.Color.Color4            35466     35466     35466     
Strip.Color.Color5            52685     33924     16448     
Strip.Color.Color6            33667     28784     65535     
Strip.Color.Color7            64250     4883      16448     
Strip.Color.Color8            65535     65535     0         
Strip.Color.Color9            49601     40092     32896     
Strip.Color.Color10           52685     33924     16448     
Strip.Option.GridXon          1
Strip.Option.GridYon          1
Strip.Option.AxisXnumTics     5
Strip.Option.AxisYnumTics     9
Strip.Option.AxisYcolorStat   1
Strip.Option.GraphLineWidth   2
Strip.Option.LegendVisible    1
Strip.Curve.0.Name            pwfs2:dc:aoZ.VALH
Strip.Curve.0.Precision       4
Strip.Curve.0.Min             -2.0000
Strip.Curve.0.Max              2.0000
Strip.Curve.0.PenStatus       1
Strip.Curve.0.PlotStatus      1
