#!/bin/sh -f
#
# Install script for Gemini PWFS1 system
#

applSetup -T svgm5 -s Makefile.subdirs -I docs -I dspsrc -I par -X sys -X ar \
          -depends /gemini/astlib -depends /gemini/slalib \
          -depends /gemini/timelib -depends /home/cboyer/wfs_lib/cfitsio-ppc \
          -depends /gemini/dhs $1 > pwfs1Build.log 2>&1

applSetup  >> pwfs1Build.log 2>&1

editUAE()
{
ed UAE.dist << eof >/dev/null
/^FILES4
a
FILES6 = ( \${APPLIC_INSTALL}/bin/asm56000 )
FILES7 = ( \${APPLIC_INSTALL}/IMP_Startup.pwfs1 )
.
w
$
a

(\${FILES6}) -> (\${HOSTS})
        install -R \${DIST_PATH}/bin/asm56000;
(\${FILES7}) -> (\${HOSTS})
        install -R \${DIST_PATH}/IMP_Startup.pwfs1;
.
w
q
eof
}

cd startup
editUAE
cd ..

gmake >> pwfs1Build.log 2>&1

exit 0

