
include ../.applTop
include $(APPLIC_TOP)/config/CONFIG

# The *.vws scripts will be edited and put in the bin/$(T_A) directory
PROD     = $(patsubst ../%.vws, %, $(wildcard ../*.vws))

# Using NFS, so create the Distfile
TARGETS += Distfile.$(T_A)

include $(APPLIC_TOP)/config/RULES.Build
