#!/usr/bin/csh -f
#
#	MODULE NAME:
#	wfsStart
#
#	FILENAME:
#	wfsStart
#
#	INVOCATION:
#	./wfsStart
#
#	PURPOSE:
#	Script for starting the Wavefront Sensing screens
#
#	DESCRIPTION
#	This script defines the EPICS display path variable, adds the directory
#	containing shell scripts and solaris binaries to the PATH and then
#	starts the top level wavefront sensing engineering screen in the background.
#
#	PRIOR REQUIREMENTS:
#	The EPICS environment variables should have been defined by executing
#	the EPICS startup script.
#	This script assumes the top level wavefront sensor directory is
#	the current directory.
#
#	DEFICIENCIES:
#	The script only works when the top level wavefront sensor directory is
#	the current directory.
#
#	AUTHOR:
#	Steven M Beard
#
#	HISTORY:
#	$Id: wfsStart2,v 1.1.1.1 1999-05-19 00:04:40 cboyer Exp $
#
#	$Log: not supported by cvs2svn $
#	Revision 1.1  1998/10/12 14:27:54  cics
#	Temporary second system files added to allow concurrent development
#
#	Revision 1.2  1998/07/17 10:49:01  smb
#	Prologue extended. More checks added.
#
#

# Check the EPICS startup script has been executed.

if ( ${?EPICS} == 0 ) then

   echo "EPICS environment variables have not been defined. Please execute" 
   echo "your local EPICS setup script."
   exit
endif

# Check that the current directory is the top level wavefront sensing
# directory (by checking for the presence of a "dl" subdirectory).

if ( !( -e ./dl ) ) then

   echo "Please cd to the top level wavefront sensing directory" 
   echo "before executing this script." 
   exit
endif

# Check that the "bin" and "data" subdirectories both exist.

if ( !( -e ./bin ) || !( -e ./data ) ) then

   echo "No bin or data directories could be found. Please build" 
   echo "the application with gmake before executing this script." 
   exit
endif

# Initialise the top level WFS directory.
# THIS IS ASSUMED TO BE THE CURRENT DIRECTORY.

setenv WFSTOP `pwd`

# If a search path for the display screens has already been defined then
#   Add the WFS directories in front of this path. 
# Else
#   Create a new display screen search path containing the WFS directories.
# Endif

if ( ${?EPICS_DISPLAY_PATH} ) then

    setenv EPICS_DISPLAY_PATH ${WFSTOP}/data:${EPICS_DISPLAY_PATH}
else

    setenv EPICS_DISPLAY_PATH ${WFSTOP}/data
    setenv EPICS_DISPLAY_PATH .:${EPICS_DISPLAY_PATH}
endif

# Add the scripts directory to the PATH so the "dm" screens can find them.

setenv PATH ${WFSTOP}/bin/solaris:${PATH}

# Finally, start the display screens in the background.

echo "Starting top level WFS screen - second system..."
dm wfs_main.dl "top=a2:wfs:, sadtop=a2:wfs" &
