# Include file identifying the target architecture (defines the T_A
# macro) and application configuration definitions

include Target.include
include .applTop/config/CONFIG

# External libraries on which this directory is dependent.
# DEPLIBS    =

# User compiler and loader flags
# USR_CFLAGS   =
# USR_INCLUDES =
# USR_LDFLAGS  =
# USR_LDLIBS   =

# Add the source code files to this variable. The default has all .c files 
# SRCS.c	= $(wildcard ../*.c) 
SRCS.c	= 

# Add the object files in one of these two variables. 
# LIBOBJS += test.o
OBJS	=  $(strip $(patsubst ../%.c,    %.o, $(SRCS.c)))

# Standard macros for files which are to be built and installed.
# PROD (products) and SCRIPTS are installed in INSTALL_BIN
# By default, don't try and build 'sys'.
# PROD	= $(notdir $(shell cd ..; pwd))
SCRIPTS	=

# LIBNAME is installed in INSTALL_LIB
LIBNAME	=

# INC is installed in INSTALL_INCLUDE
INC	=

# MAN1 is installed in INSTALL_MAN/man1
MAN1	=

# DOCS are installed in INSTALL_DOC
DOCS	=

# DATA are installed in INSTALL_DATA
DATA	= \
	$(wildcard ../*.pv*) \
	$(wildcard ../*.par*) \
	$(wildcard ../*.ini*) \
	$(wildcard ../*.control*) \
	$(wildcard ../*.fvars*) \
	$(wildcard ../*.mult*) \
	$(wildcard ../*.sub*) \
	$(wildcard ../*.wcs*) \
	$(wildcard ../*.dat*) \
	$(wildcard ../*.fits*)

# Any extra targets can be placed in a TARGETS macro (the build target
# builds only pre_build, LIBNAME, TARGETS and PROD, not SCRIPTS, INC etc)

TARGETS =

# Rules for building targets
include .applTop/config/RULES.Build

# This rule will work if there is only one target, but has to be
# modified appropriately for multiple targets

$(PROD): $(OBJS) $(DEPLIBS)
	$(RM) $@
	$(LINK.c) -o $@ $(OBJS) $(LDLIBS)
