###name of wfs: 1=PWFS1, 2=PWFS2, 3=OIWFS ; check osp.h for enum
1
###mode of wfs: active optics=0, fast guide=1 ; check osp.h for enum
0
###name of centres file for pwfs
data/nominal.13x13.16Out.dat
###name of file containing subtractive constants
data/pwfs.sub       
###name of file containing multiplicative constants
data/pwfs.mult        
###name of file containing control matrix
data/pwfs.control.cfg3.10z         
###name of file containing variances from fitting control matrix
data/pwfs.fvars.10z         
###name of file containing ao scale
data/pwfs.aoscale.10z         
###int np: max. no of Zernikes calculable 
10
###int mp: 2 x no. of subapertures used
40
###int x_arraysize: x dimension of CCD array in pixels
80
###int y_arraysize: y dimension of CCD array in pixels
80
###int xstart: 
1
###int ystart:
1
###int xbin:
1
###int ybin:
1
###int xraster: Remember that (xraster+xspace) must equal the subap pitch
13
###int yraster: Remember that (yraster+yspace) must equal the subap pitch
13
###int xspace: Remember that (xraster+xspace) must equal the subap pitch
0
###int yspace: Remember that (yraster+yspace) must equal the subap pitch
0
###int sectors: no. of sectors read out.
4
###int xsubap:
3
###int ysubap:
3
###int framesizeflag: 0 for reduced frame, 1 for fullframe 
1
###float nsigma: no. of sds above threshold (see ospThreshold())
3
###float readsq: square of read noise in e- per pixel
36
###int weight: 0 for unweighted, 1 for weighted
0
###float thresh for FG
200
###float thresh: -1 or -3 for corner averaging, >0 for global thresh
200
###float tipscale: scale factor for calculated tip, applied in osp(FG)Measure
0.1
###float tiltscale: scale factor for calculated tilt, applied etc.
0.1
###float focusscale: scale factor for calculated focus, applied etc.
-0.05
###float angle: angle factor for rotating centroids
0.0
###float xcenter
40.5
###float ycenter
40.5
###float gain for focus averaging
0.1
