# Include file identifying the target architecture (defines the T_A
# macro) and application configuration definitions

include ../.applTop
include $(APPLIC_TOP)/config/CONFIG

# External libraries on which this directory is dependent.
# DEPLIBS      =

# User compiler and loader flags (NO_EPICS flag is needed for all processors except zero)
# SNC_FLAGS    =
USR_CFLAGS = -O2 -D$(APPLIC_SITE)
# USR_INCLUDES =
# USR_LDFLAGS  =
# USR_LDLIBS   =

# Add the record include (*.h) files to this variable.
# This causes the record *.h file to be built from the record *.dbd file.
RECTYPES =

# Add dbd files to this variable for installation.
DBDINSTALL =

# Add the source code files to this variable. The default has all .c files.
#SRCS.c	= $(wildcard ../*.c)
LIBSRCS.c	= \
	../cicsCarHealth.c \
	../cicsLib.c \
	../epToVxLib.c \
	../errorLib.c \
        ../matrixLib.c \
	../aoP2Lib.c \
	../sdsuLib.c \
	../timeoutLib.c \
	../wfsLib.c \
	../wfsWcs.c\
	../writeZernikes.c

APPLSRCS.c	= \
	../drvVmi5588.c \
	../detControl.c \
	../simpleLog.c \
	../wfsControl.c \
	../wfsDb.c \
	../wfsResourceMonitor.c \
	../wfsSite.c \
	../testKit.c \
	../sdsuRead.c \
	../fpscr.c

SRCS.c	= $(LIBSRCS.c) $(APPLSRCS.c)


# Add the library object files in LIBOBJS and the product in PROD.

LIBOBJS	=  $(strip $(patsubst ../%.c,    %.o, $(LIBSRCS.c)))
OBJS	=  $(strip $(patsubst ../%.c,    %.o, $(APPLSRCS.c))             \
		   $(patsubst ../%.st,   %.o, $(wildcard ../*.st  )) \
		   $(patsubst ../%.stpp, %.o, $(wildcard ../*.stpp)))
PROD	= $(strip $(patsubst %.o, %, $(OBJS))                        \
		  $(patsubst ../%.vws, %, $(wildcard ../*.vws)))

# Standard macros for files which are to be built and installed.
# PROD (products) and SCRIPTS are installed in INSTALL_BIN
#PROD   = $(strip $(patsubst %.o, %, $(OBJS))                        \
#	$(patsubst ../%.vws, %, $(wildcard ../*.vws)))

SCRIPTS =

# LIBNAME is installed in INSTALL_LIB
LIBNAME	= wfsLibraries

# INC is installed in INSTALL_INCLUDE
INC	= \
	./cicsLib.h \
	./dbTypes.h \
	./detControl.h \
	./epToVxLib.h \
	./errorLib.h \
	./errorLog.h \
	./gemModNum.h \
	./gemTypes.h \
	./sdsuLib.h \
	./synchroMap.h \
	./sysextMemMap.h \
	./timeoutLib.h \
	./vmi5588.h \
	./wfsDb.h \
	./wfsLib.h \
	./wfsSite.h \
	./wfsControl.h \
	./wfsResourceMonitor.h \
        ./matrixLib.h \
	./aoP2Lib.h

# MAN1 is installed in INSTALL_MAN/man1
MAN1	=

# DOCS are installed in INSTALL_DOC
DOCS	=

# DATA are installed in INSTALL_DATA
DATA	= ../pwfs2.pv

# Any extra targets can be placed in a TARGETS macro (the build target
# builds only pre_build, LIBNAME, TARGETS and PROD, not SCRIPTS, INC etc)
TARGETS	=

# Rules for building targets
include $(APPLIC_TOP)/config/RULES.Build

# There is no product rule, but one can be added and edited.
#$(PROD): $(OBJS)
#	$(RM) $@
#	$(LINK.c) $@ $(OBJS)
