# Include file identifying the target architecture (defines the T_A
# macro) and application configuration definitions

include Target.include
include .applTop/config/CONFIG

# Insert this alternative compiler to use purify, otherwise comment out.
#CC = purify gcc -nostdinc
#LD = -o

# External libraries on which this directory is dependent.
# DEPLIBS	=

# User compiler and loader flags
# USR_CFLAGS   =
# USR_INCLUDES =
# USR_LDFLAGS  =
# USR_LDLIBS   =

# Add the source code files to this variable. The default has all .c files 
# SRCS.c	= $(wildcard ../*.c)
SRCS.c	= ../ospLib.c ../ospInvertFuncs.c

# Add the object files in one of these two variables. 
# LIBOBJS += test.o
OBJS	=  $(strip $(patsubst ../%.c,    %.o, $(SRCS.c)))

# Standard macros for files which are to be built and installed.
# PROD (products) and SCRIPTS are installed in INSTALL_BIN
#PROD	= $(patsubst %.o, %, $(OBJS))
PROD = ospMain
SCRIPTS	=

LDLIBS  = /home/smb/gemini_lib/cfitsio/lib/solaris/cFitsIo -lm

# LIBNAME is installed in INSTALL_LIB
LIBNAME	=

# INC is installed in INSTALL_INCLUDE
INC	=

# MAN1 is installed in INSTALL_MAN/man1
MAN1	=

# DOCS are installed in INSTALL_DOC
DOCS	=

# DATA are installed in INSTALL_DATA
DATA	= $(wildcard ../resource.def)

# Any extra targets can be placed in a TARGETS macro (the build target
# builds only pre_build, LIBNAME, TARGETS and PROD, not SCRIPTS, INC etc)

TARGETS =

# Rules for building targets
include .applTop/config/RULES.Build

# There is no product rule, but one can be added or modified if required
$(PROD): $(OBJS) $(DEPLIBS)
	$(RM) $@
	$(LINK.c) -o $@ $(OBJS) $(LDLIBS)
