#!/bin/csh -f
#
# Description :
#    C-shell script for converting source code for the WFS libraries into
#    software manuals with the aid of wflman.
#
#    To make the script simpler, every document is given the same version
#    number. The current version number is stored in a file "version.dat"
#    and incremented each time the script is executed. To reset the version
#    number to 1 delete "version.dat".
#
# Deficiencies:
#    The version numbers need to be edited by hand. It would be nice if
#    this script could automatically increment the version number each time
#    a new set of documentation is made.
#
# Usage:
#    makeDocumentation
#

#
#  Go to the documentation directory
#

   set olddir = $cwd
   cd ./.applTop/docs

#
#  Find out the current version number and increment it, storing it in the
#  file "version.dat" and starting at 1 if the file does not exist.
#

   if ( -e version.dat ) then

      set version = `cat version.dat`
      set version = `expr $version + 1`
      rm -f version.dat
   else

      set version = 1
   endif
   echo $version >version.dat

#
#  Execute the script to generate the software manuals for each library.
#
   echo Generating version $version of the software manuals.

   echo Generating software manual for sdsuLib.
   ./wflman_make_doc sdsuLib "N Dillon, A N Johnson and S M Beard" "nd" "Detector Controller VxWorks Library" "003" "$version"

   echo Generating software manual for epToVxLib.
   ./wflman_make_doc epToVxLib "N Dillon and S M Beard" "nd" "EPICS to VxWorks Communication Library" "009" "$version"

   echo Generating software manual for sysextLib.
   ./wflman_make_doc sysextLib "N Dillon" "nd" "VxWorks System Library Extensions" "010" "$version"

   echo Generating software manual for mpPipeDrv.
   ./wflman_make_doc mpPipeDrv "N Dillon" "nd" "Multi-Processor Pipe Driver" "011" "$version"

   echo Generating software manual for errorLib.
   ./wflman_make_doc errorLib "S M Beard and N Dillon" "smb" "Error Handling Library" "004" "$version"

   echo Generating software manual for timeoutLib.
   ./wflman_make_doc timeoutLib "S M Beard and N Dillon" "smb" "Timeout Handling Library" "005" "$version"

   echo Generating software manual for wfsLib.
   ./wflman_make_doc wfsLib "S M Beard and N Dillon" "smb" "Wavefront Sensing Task Library" "006" "$version"

#
#  Finally, restore the original current directory.
#

   cd $olddir
