/*+
 * MODULE NAME:
 * wfsDb
 *
 * FILENAME:
 * wfsDb.c
 *
 * PURPOSE:
 * PWFS1 database definition
 *
 * DESCRIPTION:
 * This module initialises the data structures which describe the records
 * contained in the EPICS database and the properties of the commands
 * associated with those records. The data structure arrays are declared in
 * "wfsDb.h" and their contents declared in "dbTypes.h". A record cannot
 * by accessed by the epToVxLib library unless it is declared here.
 *
 * The database is initialised in wfsDb.c rather than wfsDb.h because of
 * the programming convention that header files only declare objects and do
 * not allocate memory space
 *
 * FUNCTION NAME(S):
 * None
 *
 * DEFICIENCIES:
 * This module assumes that all EPICS records have the same prefix.
 *
 * The default values of attributes for the detGeometry command should be set to
 * values derived from the detector properties rather than fixed values. 
 *
 * NOTE:
 * This file only defines the records that the WFS epToVxLib library needs to
 * know about. There may be other EPICS records - see the Capfast schematics.
 *
 * I am concerned that all the EPICS database definitions need to be
 * duplicated here and in the Capfast schematics, as there is a risk the
 * two definitions will diverge. Can the database information be extracted
 * from the files generated from the Capfast schematics, or at least
 * downloaded from a file or defined in function calls at boot time?
 * SMB - 26 Nov 97.
 *
 * Note that the initialisers in this module do not necessarily fill
 * all of a CAD record structure. For example, if a CAD record does not
 * have any attributes, then its attribute structure is not initialised.
 * This feature may generate warnings with some compilers. It is assumed
 * that uninitialised parts of the data structures will be filled with
 * zero or NULL values.
 *
 * IMPORTANT:
 * The record names and fields declared in this file should exactly
 * match the names and fields for those same records as defined in
 * the Capfast schematics
 *
 * ORIGINAL AUTHOR:
 * Nick Dillon
 *
 * MODIFIED BY:
 * Steven Beard
 *
 * HISTORY MODIFICATIONS
 * 29 Mar 2004 - cb Remove aoThreshold detSigInitAoGain, create 
 *                  detSigInitAoThresh
 * 04 Feb 2003 - cb Add aoThreshold detSigInitAoGain
 * 08 Oct 2002 - cb add detPowerOff
 * 24 Sep 2002 - cb Implement seeing computation according FR's method (add r0,
 *                  jitter + seeingCoeffVectInit SIR records, detSigInit 
 *                  modified)
 * 18 Jun 2002 - cb Implement seeing computation (seeing SIR record, detSigInit
 *                  modified)
 * 24 Apr 2002 - cb add fgTipGain, fgTiltGain, fgFocusGain, cfFocusBw, 
 *                  cfTipTiltBw sir records
 * 21 Mar 2002 - cb modify init and detReset
 * 18 Jan 2002 - cb add detPowerOn
 * 14 Dec 2001 - cb add rms sir record
 * 30 Nov 2001 - cb add writeToRm parameter to GG and FG CADs
 * 22 Aug 2001 - cb Major modifications to have aO correction with pwfs2
 * 02 Apr 2001 - cb add adc0, adc1, adc2, adc3
 * 20 Feb 2001 - cb add dhsCon sir record
 * 10 Jan 2001 - cb detSigInit according to the site
 * 11 Dec 2000 - cb add detSigReset
 * 30 Oct 2000 - cb add detSigInitBW
 * 12 Apr 2000 - cb add detType, detID, dataLabel, intTime, nexpRQ,
 *                  nexp, nframes, bunit, exposedRQ, exposed, utstart, 
 *                  utend, elapsed sir records
 * 11 Apr 2000 - cb replace detSigMode by a set of CAD
 * 07 Apr 2000 - cb add parameters to detSigMode 
 * 30 Mar 2000 - cb add detFrameSize 
 * 22 Mar 2000 - cb remove detSetup
 * 08 Mar 2000 - cb tidy up, and replace detInit and detTest with init 
 *                  and test after deleting the original init and test
 *
 *-
 */

/* includes */

#ifdef vxWorks
#include <vxWorks.h>
#else
#error This code only runs under VxWorks
#endif /* vxWorks */


#include "dbTypes.h"
#include "wfsDb.h"
#include "wfsLib.h"
#include "epToVxLib.h"
#include "detControl.h"   /* This is where DET_CONTROL_ parameters come from. */
#include "wfsControl.h"   /* This is where WFS_CONTROL_ parameters come from. */
#include "errorLog.h"     /* This is where LOGTASK_ parameters comes from.    */


/* The pWfsDbCadList data structure array contains information on the CAD records
 * recognised by the system, and the commands associated with them. Each
 * CAD record is described by the following information:
 * - Record name (excluding the system prefix).
 * - Name of task to receive commands from that record.
 * - Command number associated with that record.
 * - Flag indicating whether the stop directive is supported.
 * - Flag indicating whether the command can run in simulation mode.
 * - Command timeout in seconds.
 * - List of command attributes, together with the data type, default value
 *   and allowed range for each attribute. There can be zero or more attributes.
 */

CAD_RECORD pWfsDbCadList [] =
{
 {
  RECORD_NAME ("reboot"),
  WFS_CONTROL_TASK_NAME,
  WFS_CONTROL_CMD_REBOOT,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  NO_TIMEOUT
 },
 {
  RECORD_NAME ("park"),
  WFS_CONTROL_TASK_NAME,
  WFS_CONTROL_CMD_PARK,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  NO_TIMEOUT
 },
 {
  RECORD_NAME ("simulate"),
  WFS_CONTROL_TASK_NAME,
  WFS_CONTROL_CMD_SIMULATE,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_UNSUPPORTED,
  10.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_LONG,  ATTRIB (EPTOVX_SIM_MODE_NONE), {ATTRIB (EPTOVX_SIM_MODE_VSM), ATTRIB (EPTOVX_SIM_MODE_NONE)}
 },
 {
  RECORD_NAME ("debug"),
  WFS_CONTROL_TASK_NAME,
  WFS_CONTROL_CMD_DEBUG,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_UNSUPPORTED,
  10.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_LONG,  ATTRIB (EPTOVX_DEBUG_MODE_NONE),
                {ATTRIB (EPTOVX_DEBUG_MODE_NONE),
                ATTRIB (EPTOVX_DEBUG_MODE_FULL)}
 },
 {
  RECORD_NAME ("init"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_INITIALISE,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  180.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_LONG,ATTRIB (DET_CONTROL_PWFS2_SDSU_ADRS_VME), {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_B, EPICS_DATA_TYPE_STRING, DET_CONTROL_OMF_FILE_PATH, {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_C, EPICS_DATA_TYPE_STRING, DET_CONTROL_OMF_VME_FILE, {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_D, EPICS_DATA_TYPE_STRING, "tim-39.lod", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_E, EPICS_DATA_TYPE_STRING, "util-39.lod", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_F, EPICS_DATA_TYPE_LONG, ATTRIB (DET_CONTROL_PWFS2_MAX_FRAMES), {"0", "100"},
  CAD_ATTRIB_G, EPICS_DATA_TYPE_LONG,"1" , {"0", "1"},
  CAD_ATTRIB_H, EPICS_DATA_TYPE_LONG,"0" , {"0", "1"}
 },
 {
  RECORD_NAME ("test"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_TEST,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  120.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_LONG, "8", {"0", "8"},
  CAD_ATTRIB_B, EPICS_DATA_TYPE_LONG, "0", {"0", "1"}
 },
 {
  RECORD_NAME ("dc:detChop"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_CHOP,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  40.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_LONG,  "0",   {"0", "7"}
 },
 {
  RECORD_NAME ("dc:detFrameSize"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_FRAME_SIZE,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  40.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_LONG, "0", {"0", "1"}
 },
 {
  RECORD_NAME ("dc:detDhsReconnect"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_DHS_RECONNECT,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  NO_TIMEOUT,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_LONG, "0", {"0", "1"}
 },
 {
  RECORD_NAME ("dc:detDhsDisplay"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_DHS_DISPLAY,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  40.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_LONG, "100", {"1", "500"}
 },
 {
  RECORD_NAME ("dc:detExposure"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_EXPOSURE,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  30.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_LONG,  "-1",   {"-1", NO_HI_LIMIT},
  CAD_ATTRIB_B, EPICS_DATA_TYPE_DOUBLE,  "0.1",   {"0.005", "10000.0"}
 },
 {
  RECORD_NAME ("dc:detObstype"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_OBS_TYPE,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  40.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_STRING,  "UNDEFINED",   {"DARK","FLAT","ZERO","UNDEFINED","OBJECT"},
 },
 {
  RECORD_NAME ("dc:detSetWcs"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_SET_WCS,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  120.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_STRING,  DET_CONTROL_PAR_FILE_PATH, {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_B, EPICS_DATA_TYPE_STRING,  "p2calib.wcs",    {NO_ATTRIBUTE_LIMITS}
 },
 {
  RECORD_NAME ("dc:observe"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_OBSERVE,
  STOP_DIRECTIVE_SUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  180.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_LONG,  "-1",   {"-1", NO_HI_LIMIT},
  CAD_ATTRIB_B, EPICS_DATA_TYPE_DOUBLE,  "0.01",   {"0.005", "10000.0"},
  CAD_ATTRIB_C, EPICS_DATA_TYPE_LONG,  "0",      {"0", "2"},
  CAD_ATTRIB_D, EPICS_DATA_TYPE_STRING,  "NONE",      {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_E, EPICS_DATA_TYPE_LONG,  "2",      {"0", "2"},
  CAD_ATTRIB_F, EPICS_DATA_TYPE_STRING,  DET_CONTROL_DATA_FILE_PATH, {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_G, EPICS_DATA_TYPE_STRING,  "pwfs2.fits",    {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_H, EPICS_DATA_TYPE_STRING,  "NONE",      {NO_ATTRIBUTE_LIMITS}
 },
 {
  RECORD_NAME ("dc:stop"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_STOP,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  120.0
 },
 {
  RECORD_NAME ("dc:abort"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_ABORT,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  120.0
 },
 {
  RECORD_NAME ("dc:detReset"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_RESET,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  60.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_LONG,  "1",       {"0", "1"},
  CAD_ATTRIB_B, EPICS_DATA_TYPE_LONG,  "1",       {"0", "1"},
  CAD_ATTRIB_C, EPICS_DATA_TYPE_STRING, DET_CONTROL_OMF_FILE_PATH,  {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_D, EPICS_DATA_TYPE_STRING, DET_CONTROL_OMF_VME_FILE,  {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_E, EPICS_DATA_TYPE_LONG, "0", {"0","1"}
 },
 {
  RECORD_NAME ("dc:detSave"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_SAVE,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  120.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_STRING,  DET_CONTROL_PAR_FILE_PATH, {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_B, EPICS_DATA_TYPE_STRING,  "p2newparams.par",   {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_C, EPICS_DATA_TYPE_LONG,  "-1",      {"-1", "3"}
 },
 {
  RECORD_NAME ("dc:detGeometry"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_GEOMETRY,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  40.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_LONG,  "1",   {"1", "20"},
  CAD_ATTRIB_B, EPICS_DATA_TYPE_LONG,  "1",   {"1", "20"},
  CAD_ATTRIB_C, EPICS_DATA_TYPE_LONG,  "40",   {"1", ATTRIB (CCD_XSIZE)},
  CAD_ATTRIB_D, EPICS_DATA_TYPE_LONG,  "40",   {"1", ATTRIB (CCD_YSIZE)},
  CAD_ATTRIB_E, EPICS_DATA_TYPE_LONG,  "1",   {"1", ATTRIB (CCD_XSIZE)},
  CAD_ATTRIB_F, EPICS_DATA_TYPE_LONG,  "1",   {"1", ATTRIB (CCD_YSIZE)},
  CAD_ATTRIB_G, EPICS_DATA_TYPE_LONG,  "0",   {"0", ATTRIB (CCD_XSIZE)},
  CAD_ATTRIB_H, EPICS_DATA_TYPE_LONG,  "0",   {"0", ATTRIB (CCD_YSIZE)},
  CAD_ATTRIB_I, EPICS_DATA_TYPE_LONG,  "0",   {"0", ATTRIB (CCD_XSIZE)},
  CAD_ATTRIB_J, EPICS_DATA_TYPE_LONG,  "0",   {"0", ATTRIB (CCD_YSIZE)}
 },
 {
  RECORD_NAME ("dc:detPrim"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_PRIMITIVE,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  60.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_STRING, "TDL",   {NO_ATTRIBUTE_LIMITS},
                   /* Allow any command. */
  CAD_ATTRIB_B, EPICS_DATA_TYPE_LONG,  "1",   {"1", "3"},
  CAD_ATTRIB_C, EPICS_DATA_TYPE_LONG,  "0x55aaff",  {"0", NO_HI_LIMIT},
  CAD_ATTRIB_D, EPICS_DATA_TYPE_LONG,  "0",   {"0", NO_HI_LIMIT},
  CAD_ATTRIB_E, EPICS_DATA_TYPE_LONG,  "0",   {"0", NO_HI_LIMIT},
  CAD_ATTRIB_F, EPICS_DATA_TYPE_LONG,  "0",   {"0", NO_HI_LIMIT},
  CAD_ATTRIB_G, EPICS_DATA_TYPE_LONG,  "0",   {"0", NO_HI_LIMIT},
  CAD_ATTRIB_H, EPICS_DATA_TYPE_LONG,  "0",   {"0", NO_HI_LIMIT}
 },
 {
  RECORD_NAME ("dc:detMode"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_MODE,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  40.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_LONG,  "-1",   {"-1", NO_HI_LIMIT},
  CAD_ATTRIB_B, EPICS_DATA_TYPE_LONG,  "-1",   {"-1", NO_HI_LIMIT},
  CAD_ATTRIB_C, EPICS_DATA_TYPE_LONG,  "-1",   {"-1", "0xFFF"},
  CAD_ATTRIB_D, EPICS_DATA_TYPE_LONG,  "-1",   {"-1", NO_HI_LIMIT}
 },
 {
  RECORD_NAME ("dc:detOffset"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_OFFSET,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  40.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_LONG,  "-1",   {"-1", NO_HI_LIMIT},
  CAD_ATTRIB_B, EPICS_DATA_TYPE_LONG,  "-1",   {"-1", NO_HI_LIMIT},
  CAD_ATTRIB_C, EPICS_DATA_TYPE_LONG,  "-1",   {"-1", NO_HI_LIMIT},
  CAD_ATTRIB_D, EPICS_DATA_TYPE_LONG,  "-1",   {"-1", NO_HI_LIMIT}
 },
 {
  RECORD_NAME ("dc:detTemp"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_TEMP,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  40.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_DOUBLE,  "-20",   {"-63", "25"},
  CAD_ATTRIB_B, EPICS_DATA_TYPE_LONG,  "0x80",   {NO_ATTRIBUTE_LIMITS}
 },
 {
  RECORD_NAME ("dc:detPowerOn"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_POWER_ON,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  40.0
 },
 {
  RECORD_NAME ("dc:detPowerOff"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_POWER_OFF,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  40.0
 },
 {
  RECORD_NAME ("dc:detSigReset"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_SIG_RESET,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  40.0
 },
#if (MK)
 {
  RECORD_NAME ("dc:detSigInit"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_SIG_INIT,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  300.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_STRING,  DET_CONTROL_PAR_FILE_PATH,  {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_B, EPICS_DATA_TYPE_STRING, "defFullP2DarkMK.fits", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_C, EPICS_DATA_TYPE_STRING, "defFullP2FlatMK.fits", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_D, EPICS_DATA_TYPE_DOUBLE,  "0.0",  {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_E, EPICS_DATA_TYPE_DOUBLE,  "40.5",  {"0.5", "80.5"},
  CAD_ATTRIB_F, EPICS_DATA_TYPE_DOUBLE,  "40.5",  {"0.5", "80.5"},
  CAD_ATTRIB_G, EPICS_DATA_TYPE_DOUBLE,  "0.0", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_H, EPICS_DATA_TYPE_STRING, "defFullRefP2.dat", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_I, EPICS_DATA_TYPE_STRING, "defAoIntMatP2MK.dat", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_J, EPICS_DATA_TYPE_STRING, "defAoContMatP2MK.dat", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_K, EPICS_DATA_TYPE_STRING, "defFgContMatP2MK.dat", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_L, EPICS_DATA_TYPE_DOUBLE,  "1.0", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_M, EPICS_DATA_TYPE_STRING, "defSeeingCoeffMatP2MK.dat", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_N, EPICS_DATA_TYPE_STRING, "defSeeingCoeffVectP2MK.dat", {NO_ATTRIBUTE_LIMITS}
 },
#else
 {
  RECORD_NAME ("dc:detSigInit"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_SIG_INIT,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  300.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_STRING,  DET_CONTROL_PAR_FILE_PATH,  {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_B, EPICS_DATA_TYPE_STRING, "defFullP2DarkCP.fits", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_C, EPICS_DATA_TYPE_STRING, "defFullP2FlatCP.fits", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_D, EPICS_DATA_TYPE_DOUBLE,  "0.0",  {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_E, EPICS_DATA_TYPE_DOUBLE,  "40.5",  {"0.5", "80.5"},
  CAD_ATTRIB_F, EPICS_DATA_TYPE_DOUBLE,  "40.5",  {"0.5", "80.5"},
  CAD_ATTRIB_G, EPICS_DATA_TYPE_DOUBLE,  "0.0", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_H, EPICS_DATA_TYPE_STRING, "defFullRefP2.dat", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_I, EPICS_DATA_TYPE_STRING, "defAoIntMatP2CP.dat", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_J, EPICS_DATA_TYPE_STRING, "defAoContMatP2CP.dat", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_K, EPICS_DATA_TYPE_STRING, "defFgContMatP2CP.dat", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_L, EPICS_DATA_TYPE_DOUBLE,  "1.0", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_M, EPICS_DATA_TYPE_STRING, "defSeeingCoeffMatP2CP.dat", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_N, EPICS_DATA_TYPE_STRING, "defSeeingCoeffVectP2CP.dat", {NO_ATTRIBUTE_LIMITS}
 },
#endif
 {
  RECORD_NAME ("dc:detSigInitAoGain"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_SIG_INIT_AO_GAIN,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  180.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_DOUBLE, "0.0", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_B, EPICS_DATA_TYPE_DOUBLE, "0.0", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_C, EPICS_DATA_TYPE_DOUBLE, "0.0", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_D, EPICS_DATA_TYPE_DOUBLE, "0.2", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_E, EPICS_DATA_TYPE_DOUBLE, "0.2", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_F, EPICS_DATA_TYPE_DOUBLE, "1.0", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_G, EPICS_DATA_TYPE_DOUBLE, "1.0", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_H, EPICS_DATA_TYPE_DOUBLE, "0.0", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_I, EPICS_DATA_TYPE_DOUBLE, "0.0", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_J, EPICS_DATA_TYPE_DOUBLE, "0.0", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_K, EPICS_DATA_TYPE_DOUBLE, "0.0", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_L, EPICS_DATA_TYPE_DOUBLE, "0.0", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_M, EPICS_DATA_TYPE_DOUBLE, "0.0", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_N, EPICS_DATA_TYPE_DOUBLE, "0.0", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_O, EPICS_DATA_TYPE_DOUBLE, "0.0", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_P, EPICS_DATA_TYPE_DOUBLE, "0.0", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_Q, EPICS_DATA_TYPE_DOUBLE, "0.0", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_R, EPICS_DATA_TYPE_DOUBLE, "0.0", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_S, EPICS_DATA_TYPE_DOUBLE, "0.0", {NO_ATTRIBUTE_LIMITS}
 },
#if (MK)
 {
  RECORD_NAME ("dc:detSigInitFgGain"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_SIG_INIT_FG_GAIN,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  180.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_DOUBLE, "0.1", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_B, EPICS_DATA_TYPE_DOUBLE, "0.1", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_C, EPICS_DATA_TYPE_DOUBLE, "0.0002", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_D, EPICS_DATA_TYPE_DOUBLE, "0.0003", {NO_ATTRIBUTE_LIMITS}
 },
#else
 {
  RECORD_NAME ("dc:detSigInitFgGain"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_SIG_INIT_FG_GAIN,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  180.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_DOUBLE, "0.1", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_B, EPICS_DATA_TYPE_DOUBLE, "0.1", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_C, EPICS_DATA_TYPE_DOUBLE, "0.0001", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_D, EPICS_DATA_TYPE_DOUBLE, "0.0003", {NO_ATTRIBUTE_LIMITS}
 },
#endif
 {
  RECORD_NAME ("dc:detSigInitBw"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_SIG_INIT_BW,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  180.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_DOUBLE, "10.0", {"0.0","20"},
  CAD_ATTRIB_B, EPICS_DATA_TYPE_DOUBLE, ".0167", {"0.0","0.1"}
 },
 {
  RECORD_NAME ("dc:detSigModeNone"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_SIG_MODE_NONE,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  40.0
 },
 {
  RECORD_NAME ("dc:detSigModeDark"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_SIG_MODE_DARK,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  40.0
 },
 {
  RECORD_NAME ("dc:detSigModeGg"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_SIG_MODE_GG,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  40.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_LONG, "1", {"0", "1"}
 },
 {
  RECORD_NAME ("dc:detSigModeFgFoc"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_SIG_MODE_FG_FOCUS,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  40.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_LONG, "0", {"0", "4"},
  CAD_ATTRIB_B, EPICS_DATA_TYPE_LONG, "1", {"0", "1"},
  CAD_ATTRIB_C, EPICS_DATA_TYPE_LONG, "1", {"0", "1"},
  CAD_ATTRIB_D, EPICS_DATA_TYPE_DOUBLE, "15.0", {"0.0", "100.0"},
  CAD_ATTRIB_E, EPICS_DATA_TYPE_DOUBLE, "2.5", {"0.0", NO_HI_LIMIT}
 },
#if (MK)
 {
  RECORD_NAME ("dc:detSigModeAo"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_SIG_MODE_AO,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  40.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_DOUBLE, "30.0", {"0.005", NO_HI_LIMIT},
  CAD_ATTRIB_B, EPICS_DATA_TYPE_LONG, "0", {"0", "4"},
  CAD_ATTRIB_C, EPICS_DATA_TYPE_DOUBLE, "10.0", {"0.0", NO_HI_LIMIT}
 },
 {
  RECORD_NAME ("dc:detSigModeGgAo"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_SIG_MODE_GG_AO,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  40.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_DOUBLE, "30.0", {"0.005", NO_HI_LIMIT},
  CAD_ATTRIB_B, EPICS_DATA_TYPE_LONG, "0", {"0", "4"},
  CAD_ATTRIB_C, EPICS_DATA_TYPE_LONG, "1", {"0", "1"},
  CAD_ATTRIB_D, EPICS_DATA_TYPE_DOUBLE, "10.0", {"0.0", NO_HI_LIMIT}
 },
 {
  RECORD_NAME ("dc:detSigModeFgFocAo"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_SIG_MODE_FG_FOCUS_AO,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  40.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_DOUBLE, "30.0", {"0.005", NO_HI_LIMIT},
  CAD_ATTRIB_B, EPICS_DATA_TYPE_LONG, "0", {"0", "4"},
  CAD_ATTRIB_C, EPICS_DATA_TYPE_LONG, "1", {"0", "1"},
  CAD_ATTRIB_D, EPICS_DATA_TYPE_LONG, "1", {"0", "1"},
  CAD_ATTRIB_E, EPICS_DATA_TYPE_DOUBLE, "15.0", {"0.0", "100.0"},
  CAD_ATTRIB_F, EPICS_DATA_TYPE_DOUBLE, "2.5", {"0.0", NO_HI_LIMIT},
  CAD_ATTRIB_G, EPICS_DATA_TYPE_DOUBLE, "10.0", {"0.0", NO_HI_LIMIT}
 },
#else
 {
  RECORD_NAME ("dc:detSigModeAo"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_SIG_MODE_AO,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  40.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_DOUBLE, "40.0", {"0.005", NO_HI_LIMIT},
  CAD_ATTRIB_B, EPICS_DATA_TYPE_LONG, "0", {"0", "4"},
  CAD_ATTRIB_C, EPICS_DATA_TYPE_DOUBLE, "10.0", {"0.0", NO_HI_LIMIT}
 },
 {
  RECORD_NAME ("dc:detSigModeGgAo"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_SIG_MODE_GG_AO,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  40.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_DOUBLE, "40.0", {"0.005", NO_HI_LIMIT},
  CAD_ATTRIB_B, EPICS_DATA_TYPE_LONG, "0", {"0", "4"},
  CAD_ATTRIB_C, EPICS_DATA_TYPE_LONG, "1", {"0", "1"},
  CAD_ATTRIB_D, EPICS_DATA_TYPE_DOUBLE, "10.0", {"0.0", NO_HI_LIMIT}
 },
 {
  RECORD_NAME ("dc:detSigModeFgFocAo"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_SIG_MODE_FG_FOCUS_AO,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  40.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_DOUBLE, "40.0", {"0.005", NO_HI_LIMIT},
  CAD_ATTRIB_B, EPICS_DATA_TYPE_LONG, "0", {"0", "4"},
  CAD_ATTRIB_C, EPICS_DATA_TYPE_LONG, "1", {"0", "1"},
  CAD_ATTRIB_D, EPICS_DATA_TYPE_LONG, "1", {"0", "1"},
  CAD_ATTRIB_E, EPICS_DATA_TYPE_DOUBLE, "15.0", {"0.0", "100.0"},
  CAD_ATTRIB_F, EPICS_DATA_TYPE_DOUBLE, "2.5", {"0.0", NO_HI_LIMIT},
  CAD_ATTRIB_G, EPICS_DATA_TYPE_DOUBLE, "10.0", {"0.0", NO_HI_LIMIT}
 },
#endif
 {
  RECORD_NAME ("dc:detSigModeCoadd"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_SIG_MODE_COADD,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  40.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_LONG, "100", {"1", NO_HI_LIMIT},
  CAD_ATTRIB_B, EPICS_DATA_TYPE_STRING, DET_CONTROL_PAR_FILE_PATH, {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_C, EPICS_DATA_TYPE_STRING, "coadd.fits", {NO_ATTRIBUTE_LIMITS}
 },
 {
  RECORD_NAME ("dc:detSigModeFgCoadd"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_SIG_MODE_FG_FOCUS_COADD,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  40.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_LONG, "0", {"0", "4"},
  CAD_ATTRIB_B, EPICS_DATA_TYPE_LONG, "100", {"1", NO_HI_LIMIT},
  CAD_ATTRIB_C, EPICS_DATA_TYPE_STRING, DET_CONTROL_PAR_FILE_PATH, {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_D, EPICS_DATA_TYPE_STRING, "coadd.fits", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_E, EPICS_DATA_TYPE_LONG, "1", {"0", "1"},
  CAD_ATTRIB_F, EPICS_DATA_TYPE_LONG, "1", {"0", "1"},
  CAD_ATTRIB_G, EPICS_DATA_TYPE_DOUBLE, "15.0", {"0.0", "100.0"},
  CAD_ATTRIB_H, EPICS_DATA_TYPE_DOUBLE, "2.5", {"0.0", NO_HI_LIMIT}
 },
 {
  RECORD_NAME ("dc:detSigModeThresh"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_SIG_MODE_THRESH,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  40.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_LONG, "0", {"0", "2"},
  CAD_ATTRIB_B, EPICS_DATA_TYPE_LONG, "100", {"1", NO_HI_LIMIT},
  CAD_ATTRIB_C, EPICS_DATA_TYPE_DOUBLE, "15.0", {"0.0", "100.0"},
  CAD_ATTRIB_D, EPICS_DATA_TYPE_DOUBLE, "2.5", {"0.0", NO_HI_LIMIT},
  CAD_ATTRIB_E, EPICS_DATA_TYPE_DOUBLE, "50", {"0.0", "65536.0"},
  CAD_ATTRIB_F, EPICS_DATA_TYPE_LONG, "1", {"0", "1"}
 },
 {
  RECORD_NAME ("dc:detSigModeGgCoadd"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_SIG_MODE_GG_COADD,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  40.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_LONG, "100", {"1", NO_HI_LIMIT},
  CAD_ATTRIB_B, EPICS_DATA_TYPE_STRING, DET_CONTROL_PAR_FILE_PATH, {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_C, EPICS_DATA_TYPE_STRING, "coadd.fits", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_D, EPICS_DATA_TYPE_LONG, "1", {"0", "1"}
 },
#if (MK)
 {
  RECORD_NAME ("dc:detSigModeSeq"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_SIG_MODE_SEQ,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  40.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_DOUBLE, "1", {"0.0", NO_HI_LIMIT},
  CAD_ATTRIB_B, EPICS_DATA_TYPE_DOUBLE, "10.0", {"0.0", NO_HI_LIMIT},
  CAD_ATTRIB_C, EPICS_DATA_TYPE_DOUBLE, "0", {"0.0", NO_HI_LIMIT},
  CAD_ATTRIB_D, EPICS_DATA_TYPE_DOUBLE, "0", {"0.0", NO_HI_LIMIT},
  CAD_ATTRIB_E, EPICS_DATA_TYPE_DOUBLE, "0", {"0.0", NO_HI_LIMIT},
  CAD_ATTRIB_F, EPICS_DATA_TYPE_DOUBLE, "0", {"0.0", NO_HI_LIMIT},
  CAD_ATTRIB_G, EPICS_DATA_TYPE_DOUBLE, "0", {"0.0", NO_HI_LIMIT},
  CAD_ATTRIB_H, EPICS_DATA_TYPE_LONG, "0", {"0", "4"},
  CAD_ATTRIB_I, EPICS_DATA_TYPE_DOUBLE, "30.0", {"0.005", NO_HI_LIMIT},
  CAD_ATTRIB_J, EPICS_DATA_TYPE_LONG, "0", {"0", "1"},
  CAD_ATTRIB_K, EPICS_DATA_TYPE_DOUBLE, "60.0", {"0.1", NO_HI_LIMIT},
  CAD_ATTRIB_L, EPICS_DATA_TYPE_LONG, "0", {"0", "1"},
  CAD_ATTRIB_M, EPICS_DATA_TYPE_DOUBLE, "0.1", {"0.1", NO_HI_LIMIT},
  CAD_ATTRIB_N, EPICS_DATA_TYPE_STRING, DET_CONTROL_DATA_FILE_PATH, {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_O, EPICS_DATA_TYPE_LONG, "1", {"0", "1"},
  CAD_ATTRIB_P, EPICS_DATA_TYPE_LONG, "1", {"0", "1"},
  CAD_ATTRIB_Q, EPICS_DATA_TYPE_LONG, "1", {"0", "1"},
  CAD_ATTRIB_R, EPICS_DATA_TYPE_DOUBLE, "15.0", {"0.0", "100.0"},
  CAD_ATTRIB_S, EPICS_DATA_TYPE_DOUBLE, "2.5", {"0.0", NO_HI_LIMIT},
  CAD_ATTRIB_T, EPICS_DATA_TYPE_LONG, "1", {"0", "1"}
 },
#else
 {
  RECORD_NAME ("dc:detSigModeSeq"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_SIG_MODE_SEQ,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  40.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_DOUBLE, "1", {"0.0", NO_HI_LIMIT},
  CAD_ATTRIB_B, EPICS_DATA_TYPE_DOUBLE, "10.0", {"0.0", NO_HI_LIMIT},
  CAD_ATTRIB_C, EPICS_DATA_TYPE_DOUBLE, "0", {"0.0", NO_HI_LIMIT},
  CAD_ATTRIB_D, EPICS_DATA_TYPE_DOUBLE, "0", {"0.0", NO_HI_LIMIT},
  CAD_ATTRIB_E, EPICS_DATA_TYPE_DOUBLE, "0", {"0.0", NO_HI_LIMIT},
  CAD_ATTRIB_F, EPICS_DATA_TYPE_DOUBLE, "0", {"0.0", NO_HI_LIMIT},
  CAD_ATTRIB_G, EPICS_DATA_TYPE_DOUBLE, "0", {"0.0", NO_HI_LIMIT},
  CAD_ATTRIB_H, EPICS_DATA_TYPE_LONG, "0", {"0", "4"},
  CAD_ATTRIB_I, EPICS_DATA_TYPE_DOUBLE, "40.0", {"0.005", NO_HI_LIMIT},
  CAD_ATTRIB_J, EPICS_DATA_TYPE_LONG, "0", {"0", "1"},
  CAD_ATTRIB_K, EPICS_DATA_TYPE_DOUBLE, "60.0", {"0.1", NO_HI_LIMIT},
  CAD_ATTRIB_L, EPICS_DATA_TYPE_LONG, "0", {"0", "1"},
  CAD_ATTRIB_M, EPICS_DATA_TYPE_DOUBLE, "0.1", {"0.1", NO_HI_LIMIT},
  CAD_ATTRIB_N, EPICS_DATA_TYPE_STRING, DET_CONTROL_DATA_FILE_PATH, {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_O, EPICS_DATA_TYPE_LONG, "1", {"0", "1"},
  CAD_ATTRIB_P, EPICS_DATA_TYPE_LONG, "1", {"0", "1"},
  CAD_ATTRIB_Q, EPICS_DATA_TYPE_LONG, "1", {"0", "1"},
  CAD_ATTRIB_R, EPICS_DATA_TYPE_DOUBLE, "15.0", {"0.0", "100.0"},
  CAD_ATTRIB_S, EPICS_DATA_TYPE_DOUBLE, "2.5", {"0.0", NO_HI_LIMIT},
  CAD_ATTRIB_T, EPICS_DATA_TYPE_LONG, "1", {"0", "1"}
 },
#endif
 {
  RECORD_NAME ("dc:detSigModeTotal"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_SIG_MODE_TOTAL,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  40.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_LONG, "0", {"0", "2"},
  CAD_ATTRIB_B, EPICS_DATA_TYPE_DOUBLE, "0.0", {"0.0", NO_HI_LIMIT},
  CAD_ATTRIB_C, EPICS_DATA_TYPE_LONG, "100", {"1", NO_HI_LIMIT},
  CAD_ATTRIB_D, EPICS_DATA_TYPE_DOUBLE, "10.0", {"0.0", "100.0"},
  CAD_ATTRIB_E, EPICS_DATA_TYPE_LONG, "1", {"0", "1"}
 },
 {
  RECORD_NAME ("dc:detSigSaveCb"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_SIG_SAVE_CB,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  40.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_LONG, "0", {"0", "1"},
  CAD_ATTRIB_B, EPICS_DATA_TYPE_LONG, "0", {"0", "1"},
  CAD_ATTRIB_C, EPICS_DATA_TYPE_LONG, "0", {"0", "1"},
  CAD_ATTRIB_D, EPICS_DATA_TYPE_STRING, DET_CONTROL_DATA_FILE_PATH, {NO_ATTRIBUTE_LIMITS}
 },
 {
  RECORD_NAME ("dc:detSigMeasAoIm"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_SIG_MEAS_AO_IM,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  40.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_LONG, "0", {"0", "1"},
  CAD_ATTRIB_B, EPICS_DATA_TYPE_LONG, "1", {"1", ATTRIB(AO_MODE_NB)},
  CAD_ATTRIB_C, EPICS_DATA_TYPE_DOUBLE, "1.0", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_D, EPICS_DATA_TYPE_LONG, "6000", {"1", NO_HI_LIMIT},
  CAD_ATTRIB_E, EPICS_DATA_TYPE_STRING, DET_CONTROL_PAR_FILE_PATH, {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_F, EPICS_DATA_TYPE_STRING, "coadd.fits", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_G, EPICS_DATA_TYPE_STRING, "cent.dat", {NO_ATTRIBUTE_LIMITS}
 },
 {
  RECORD_NAME ("dc:detSigCompAoMat"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_SIG_COMP_AO_MAT,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  40.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_STRING, DET_CONTROL_PAR_FILE_PATH, {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_B, EPICS_DATA_TYPE_STRING, "defAoIntMatP2.dat", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_C, EPICS_DATA_TYPE_STRING, "defAoContMatP2.dat", {NO_ATTRIBUTE_LIMITS}
 },
 {
  RECORD_NAME ("dc:detSigModeSeqDark"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_SIG_MODE_SEQ_DARK,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  40.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_LONG, "100", {"1", NO_HI_LIMIT},
  CAD_ATTRIB_B, EPICS_DATA_TYPE_STRING, DET_CONTROL_PAR_FILE_PATH, {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_C, EPICS_DATA_TYPE_STRING, "coadd.fits", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_D, EPICS_DATA_TYPE_LONG, "100", {"1", NO_HI_LIMIT},
  CAD_ATTRIB_E, EPICS_DATA_TYPE_DOUBLE, "2.5", {"0.0", NO_HI_LIMIT}
 },
 {
  RECORD_NAME ("dc:detSigInitModAst"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_SIG_INIT_AST_MODEL,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  40.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_DOUBLE, "0.0", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_B, EPICS_DATA_TYPE_DOUBLE, "1.5", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_C, EPICS_DATA_TYPE_DOUBLE, "0.0", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_D, EPICS_DATA_TYPE_DOUBLE, "0.0", {"-360.0","360.0"},
  CAD_ATTRIB_E, EPICS_DATA_TYPE_DOUBLE, "0.0", {"-360.0","360.0"},
  CAD_ATTRIB_F, EPICS_DATA_TYPE_DOUBLE, "0.0", {"-360.0","360.0"},
  CAD_ATTRIB_G, EPICS_DATA_TYPE_DOUBLE, "0.0", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_H, EPICS_DATA_TYPE_DOUBLE, "0.0", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_I, EPICS_DATA_TYPE_DOUBLE, "-1.5", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_J, EPICS_DATA_TYPE_DOUBLE, "0.0", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_K, EPICS_DATA_TYPE_DOUBLE, "0.0", {"-360.0","360.0"},
  CAD_ATTRIB_L, EPICS_DATA_TYPE_DOUBLE, "0.0", {"-360.0","360.0"},
  CAD_ATTRIB_M, EPICS_DATA_TYPE_DOUBLE, "0.0", {"-360.0","360.0"},
  CAD_ATTRIB_N, EPICS_DATA_TYPE_DOUBLE, "0.0", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_O, EPICS_DATA_TYPE_LONG, "0", {"0","1"},
  CAD_ATTRIB_P, EPICS_DATA_TYPE_DOUBLE, "1.0", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_Q, EPICS_DATA_TYPE_DOUBLE, "1.0", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_R, EPICS_DATA_TYPE_DOUBLE, "0.0", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_S, EPICS_DATA_TYPE_DOUBLE, "0.0", {NO_ATTRIBUTE_LIMITS}
 },
 {
  RECORD_NAME ("dc:detSigInitModTref"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_SIG_INIT_TREF_MODEL,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  40.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_DOUBLE, "0.0", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_B, EPICS_DATA_TYPE_DOUBLE, "0.0", {"-360.0","360.0"},
  CAD_ATTRIB_C, EPICS_DATA_TYPE_DOUBLE, "0.0", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_D, EPICS_DATA_TYPE_DOUBLE, "0.0", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_E, EPICS_DATA_TYPE_DOUBLE, "0.0", {"-360.0","360.0"},
  CAD_ATTRIB_F, EPICS_DATA_TYPE_DOUBLE, "0.0", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_G, EPICS_DATA_TYPE_LONG, "0", {"0","1"}
 },
 {
  RECORD_NAME ("dc:detSigInitModComa"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_SIG_INIT_COMA_MODEL,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  40.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_DOUBLE, "0.0", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_B, EPICS_DATA_TYPE_DOUBLE, "0.0", {"-360.0","360.0"},
  CAD_ATTRIB_C, EPICS_DATA_TYPE_DOUBLE, "0.0", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_D, EPICS_DATA_TYPE_DOUBLE, "0.0", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_E, EPICS_DATA_TYPE_DOUBLE, "0.0", {"-360.0","360.0"},
  CAD_ATTRIB_F, EPICS_DATA_TYPE_DOUBLE, "0.0", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_G, EPICS_DATA_TYPE_LONG, "0", {"0","1"}
 },
 {
  RECORD_NAME ("dc:detSigInitModFoc"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_SIG_INIT_FOCUS_MODEL,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  40.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_DOUBLE, "0.0", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_B, EPICS_DATA_TYPE_DOUBLE, "0.0", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_C, EPICS_DATA_TYPE_DOUBLE, "0.0", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_D, EPICS_DATA_TYPE_DOUBLE, "0.0", {"-360.0","360.0"},
  CAD_ATTRIB_E, EPICS_DATA_TYPE_DOUBLE, "0.0", {"-360.0","360.0"},
  CAD_ATTRIB_F, EPICS_DATA_TYPE_LONG, "0", {"0","1"}
 },
 {
  RECORD_NAME ("dc:detSigInitAoThresh"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  DET_CONTROL_CMD_SIG_INIT_AO_THRESH,
  STOP_DIRECTIVE_UNSUPPORTED,
  SIMULATION_MODE_SUPPORTED,
  180.0,
  CAD_ATTRIB_A, EPICS_DATA_TYPE_DOUBLE, "0.5", {NO_ATTRIBUTE_LIMITS},
  CAD_ATTRIB_B, EPICS_DATA_TYPE_DOUBLE, "5.0", {NO_ATTRIBUTE_LIMITS}
 }
};


/* The pWfsDbGsubList data structure array contains information on the genSub records
 * recognised by the system, and the commands associated with them. Each
 * genSub record is described by the following information:
 * - Record name (excluding the system prefix).
 * - Name of task to receive commands from that record.
 * - Command number associated with that record.
 * - Command timeout in seconds.
 */

GSUB_RECORD pWfsDbGsubList [] =
{
 {
  RECORD_NAME ("dc:ttfZero"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  "p2",
  GSUB_INPUT,
  DET_CONTROL_CMD_TTFZERO,
  1.0,
  8
 },
 {
  RECORD_NAME ("dc:aoZero"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  "p2",
  GSUB_INPUT,
  DET_CONTROL_CMD_AOZERO,
  1.0,
  24
 },
 {
  RECORD_NAME ("dc:probeOffset"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  "p2",
  GSUB_INPUT,
  DET_CONTROL_CMD_PROBEOFFSET,
  1.0,
  9
 },
 {
  RECORD_NAME ("dc:ttf"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  "p2",
  GSUB_OUTPUT,
  0,
  NO_TIMEOUT,
  8
 },
 {
  RECORD_NAME ("dc:ao"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME),
  "p2",
  GSUB_OUTPUT,
  0,
  NO_TIMEOUT,
  40
 }
};


/* The pWfsDbCarList data structure array contains information on the CAR records
 * recognised by the system. Each CAR record is described by the following
 * information:
 * - Record name (excluding the system prefix).
 * - Name of task responsible for that record.
 */

CAR_RECORD pWfsDbCarList [] =
{
 {
  RECORD_NAME ("controlC"),
  WFS_CONTROL_TASK_NAME
 },
 {
  RECORD_NAME ("dc:detC"),
  TASK_NAME ("pw", DET_CONTROL_TASK_NAME)
 }
};


/* The pWfsDbSirList data structure array contains information on the SIR records
 * recognised by the system. Each SIR record is described by the following
 * information:
 * - Record name (excluding the system prefix).
 * - Record data type.
 * - Hysteresis value (optional).
 */

SIR_RECORD pWfsDbSirList [] =
{
 {
  RECORD_NAME ("name"),
  EPICS_DATA_TYPE_STRING
 },
 {
  RECORD_NAME ("state"),
  EPICS_DATA_TYPE_STRING
 },
 {
  RECORD_NAME ("health"),
  EPICS_DATA_TYPE_STRING
 },
 {
  RECORD_NAME ("controlHealth"),
  EPICS_DATA_TYPE_STRING
 },
 {
  RECORD_NAME ("version"),
  EPICS_DATA_TYPE_STRING
 },
 {
  RECORD_NAME ("debugMode"),
  EPICS_DATA_TYPE_STRING
 },
 {
  RECORD_NAME ("simMode"),
  EPICS_DATA_TYPE_STRING
 },
 {
  RECORD_NAME ("measuring"),
  EPICS_DATA_TYPE_LONG
 },
 {
  RECORD_NAME ("rebooting"),
  EPICS_DATA_TYPE_LONG
 },
 {
  RECORD_NAME ("parking"),
  EPICS_DATA_TYPE_LONG
 },
 {
  RECORD_NAME ("trackId"),
  EPICS_DATA_TYPE_LONG
 },
 {
  RECORD_NAME ("arrayS"),
  EPICS_DATA_TYPE_STRING
 },
 {
  RECORD_NAME ("historyLog"),
  EPICS_DATA_TYPE_STRING
 },
 {
  RECORD_NAME ("historyLog1"),
  EPICS_DATA_TYPE_STRING
 },
 {
  RECORD_NAME ("errorLog"),
  EPICS_DATA_TYPE_STRING
 },
 {
  RECORD_NAME ("errorLog1"),
  EPICS_DATA_TYPE_STRING
 },
 {
  RECORD_NAME ("cpuUsed00"),
  EPICS_DATA_TYPE_LONG,
  5.0
 },
 {
  RECORD_NAME ("ramUsed00"),
  EPICS_DATA_TYPE_LONG,
  2.0
 },
 {
  RECORD_NAME ("ramFreeblk00"),
  EPICS_DATA_TYPE_LONG,
  256.0
 },
 {
  RECORD_NAME ("testResults"),
  EPICS_DATA_TYPE_STRING
 },
 {
  RECORD_NAME ("dc:health"),
  EPICS_DATA_TYPE_STRING
 },
 {
  RECORD_NAME ("dc:detPrimReply"),
  EPICS_DATA_TYPE_STRING
 },
 {
  RECORD_NAME ("dc:detInitStatus"),
  EPICS_DATA_TYPE_STRING
 },
 {
  RECORD_NAME ("dc:observing"),
  EPICS_DATA_TYPE_LONG
 },
 {
  RECORD_NAME ("dc:aoCtrlInit"),
  EPICS_DATA_TYPE_STRING
 },
 {
  RECORD_NAME ("dc:aoDarkInit"),
  EPICS_DATA_TYPE_STRING
 },
 {
  RECORD_NAME ("dc:aoFlatInit"),
  EPICS_DATA_TYPE_STRING
 },
 {
  RECORD_NAME ("dc:aoContMatInit"),
  EPICS_DATA_TYPE_STRING
 },
 {
  RECORD_NAME ("dc:aoIntMatInit"),
  EPICS_DATA_TYPE_STRING
 },
 {
  RECORD_NAME ("dc:fgContMatInit"),
  EPICS_DATA_TYPE_STRING
 },
 {
  RECORD_NAME ("dc:aoRms"),
  EPICS_DATA_TYPE_DOUBLE
 },
 {
  RECORD_NAME ("dc:aoThresh"),
  EPICS_DATA_TYPE_DOUBLE
 },
 {
  RECORD_NAME ("dc:aoTotal"),
  EPICS_DATA_TYPE_DOUBLE
 },
 {
  RECORD_NAME ("dc:aoSaveCbIm"),
  EPICS_DATA_TYPE_STRING
 },
 {
  RECORD_NAME ("dc:aoSaveCbAoCtrl"),
  EPICS_DATA_TYPE_STRING
 },
 {
  RECORD_NAME ("dc:aoSaveCbFgCtrl"),
  EPICS_DATA_TYPE_STRING
 },
 {
  RECORD_NAME ("dc:aoProcessMode"),
  EPICS_DATA_TYPE_STRING
 },
 {
  RECORD_NAME ("dc:fgTipGain"),
  EPICS_DATA_TYPE_DOUBLE
 },
 {
  RECORD_NAME ("dc:fgTiltGain"),
  EPICS_DATA_TYPE_DOUBLE
 },
 {
  RECORD_NAME ("dc:fgFocusGain"),
  EPICS_DATA_TYPE_DOUBLE
 },
 {
  RECORD_NAME ("dc:fgFocusGain100"),
  EPICS_DATA_TYPE_DOUBLE
 },
 {
  RECORD_NAME ("dc:cfFocusBw"),
  EPICS_DATA_TYPE_DOUBLE
 },
 {
  RECORD_NAME ("dc:cfTipTiltBw"),
  EPICS_DATA_TYPE_DOUBLE
 },
 {
  RECORD_NAME ("dc:seeing"),
  EPICS_DATA_TYPE_DOUBLE
 },
 {
  RECORD_NAME ("dc:r0"),
  EPICS_DATA_TYPE_DOUBLE
 },
 {
  RECORD_NAME ("dc:jitter"),
  EPICS_DATA_TYPE_DOUBLE
 },
 {
  RECORD_NAME ("dc:seeingGain"),
  EPICS_DATA_TYPE_DOUBLE
 },
 {
  RECORD_NAME ("dc:seeingCoeffMatInit"),
  EPICS_DATA_TYPE_STRING
 },
 {
  RECORD_NAME ("dc:seeingCoeffVectInit"),
  EPICS_DATA_TYPE_STRING
 },
 {
  RECORD_NAME ("dc:initialising"),
  EPICS_DATA_TYPE_LONG
 },
 {
  RECORD_NAME ("dc:testing"),
  EPICS_DATA_TYPE_LONG
 },
 {
  RECORD_NAME ("dc:outputs"),
  EPICS_DATA_TYPE_LONG
 },
 {
  RECORD_NAME ("dc:detXsize"),
  EPICS_DATA_TYPE_LONG
 },
 {
  RECORD_NAME ("dc:detYsize"),
  EPICS_DATA_TYPE_LONG
 },
 {
  RECORD_NAME ("dc:xsubap"),
  EPICS_DATA_TYPE_LONG
 },
 {
  RECORD_NAME ("dc:ysubap"),
  EPICS_DATA_TYPE_LONG
 },
 {
  RECORD_NAME ("dc:xstart"),
  EPICS_DATA_TYPE_LONG
 },
 {
  RECORD_NAME ("dc:ystart"),
  EPICS_DATA_TYPE_LONG
 },
 {
  RECORD_NAME ("dc:xras"),
  EPICS_DATA_TYPE_LONG
 },
 {
  RECORD_NAME ("dc:yras"),
  EPICS_DATA_TYPE_LONG
 },
 {
  RECORD_NAME ("dc:xspace"),
  EPICS_DATA_TYPE_LONG
 },
 {
  RECORD_NAME ("dc:yspace"),
  EPICS_DATA_TYPE_LONG
 },
 {
  RECORD_NAME ("dc:xbin"),
  EPICS_DATA_TYPE_LONG
 },
 {
  RECORD_NAME ("dc:ybin"),
  EPICS_DATA_TYPE_LONG
 },
 {
  RECORD_NAME ("dc:detType"),
  EPICS_DATA_TYPE_STRING
 },
 {
  RECORD_NAME ("dc:detID"),
  EPICS_DATA_TYPE_STRING
 },
 {
  RECORD_NAME ("dc:dataLabel"),
  EPICS_DATA_TYPE_STRING
 },
 {
  RECORD_NAME ("dc:intTime"),
  EPICS_DATA_TYPE_DOUBLE
 },
 {
  RECORD_NAME ("dc:nexpRQ"),
  EPICS_DATA_TYPE_LONG
 },
 {
  RECORD_NAME ("dc:nexp"),
  EPICS_DATA_TYPE_LONG
 },
 {
  RECORD_NAME ("dc:nframes"),
  EPICS_DATA_TYPE_LONG
 },
 {
  RECORD_NAME ("dc:bunit"),
  EPICS_DATA_TYPE_STRING
 },
 {
  RECORD_NAME ("dc:exposed"),
  EPICS_DATA_TYPE_DOUBLE
 },
 {
  RECORD_NAME ("dc:elapsed"),
  EPICS_DATA_TYPE_DOUBLE
 },
 {
  RECORD_NAME ("dc:exposedRQ"),
  EPICS_DATA_TYPE_DOUBLE
 },
 {
  RECORD_NAME ("dc:utstart"),
  EPICS_DATA_TYPE_STRING
 },
 {
  RECORD_NAME ("dc:utend"),
  EPICS_DATA_TYPE_STRING
 },
 {
  RECORD_NAME ("dc:dhsCon"),
  EPICS_DATA_TYPE_STRING
 },
 {
  RECORD_NAME ("dc:adc0"),
  EPICS_DATA_TYPE_LONG
 },
 {
  RECORD_NAME ("dc:adc1"),
  EPICS_DATA_TYPE_LONG
 },
 {
  RECORD_NAME ("dc:adc2"),
  EPICS_DATA_TYPE_LONG
 },
 {
  RECORD_NAME ("dc:adc3"),
  EPICS_DATA_TYPE_LONG
 }
};

/* Determine the number of CAD, CAR and SIR records defined above. */

int  wfsDbNCadRecord  = NELEMENTS (pWfsDbCadList);
int  wfsDbNGsubRecord = NELEMENTS (pWfsDbGsubList);
int  wfsDbNCarRecord  = NELEMENTS (pWfsDbCarList);
int  wfsDbNSirRecord  = NELEMENTS (pWfsDbSirList);

/*
 * Record field names and types must be given in the order of the enums
 * nnn_RECORD_TYPE where nnn = CAD, CAR, SIR etc (see dbTypes.h). If field types
 * are listed, then the Value field must be the last one in the list, since the
 * fields are accessed in the order given here and, when writing to a record,
 * processing is triggered when the Value field is written. All record types are
 * initially un-initialised (pWfsDbRecInitialised[type] = FALSE.
 */

BOOL pWfsDbRecInitialised [N_RECORD_TYPES] = {FALSE, FALSE, FALSE, FALSE};
char pppWfsDbRecFieldName [N_RECORD_TYPES][EPICS_MAX_NFIELD_PER_RECORD][EPICS_MAX_BYTES_FIELD_NAME + 2] =
 {
  {""},            /* CAD record field names  */
  {".J", ".VALJ"},         /* genSub record field names */
  {"ID", ".IERR", ".IMSS", ".IVAL"},     /* CAR record field names  */
  {".VAL"}           /* SIR record field names  */
 };

/*
 * Initialise the flag indicating whether the EPICS database is contained on the
 * local processor. This flag is reset to TRUE by the wavefront sensor control
 * task running on the root processor.
 */

BOOL wfsDbEpicsDbIsLocal = FALSE;
