#!/bin/csh -f
#+
# Module name:
#    wfsIndent
#
# Purpose:
#    Format one or more AGWPS source files
#
# Language:
#    Unix C shell script
#
# Description:
#    Use indent to generate more readable versions of the AGWPS source
#
# Invocation:
#    wfsIndent *.c     (for example)
#
# Prior requirements:
#
# Status:
#    $Id: wfsIndent,v 1.2 1999-07-17 02:14:24 cboyer Exp $
#
# History:
#    $Log: not supported by cvs2svn $
#    Revision 1.1  1998/11/30 15:55:26  cics
#    Scripts added during SMB visit to Hilo, November 1998
#
#
#-

   set files = "$*"
   if ( "$files" != "" ) then

     foreach file ( $files )

	set base=`basename $file .c`
	set output=${base}.indent
        echo Indenting $file to $output
	cat $file | tr '\t' ' ' | indent -gnu -bl -bli0 -i4 -ts80 -l80 - -o $output

     end
   else
      echo Usage - wfsIndent file1.c file2.c, file3.c ...
   endif
